services:
    _defaults:
        autowire: true
        autoconfigure: true

doctrine:
    dbal:
        default_connection: infra
        connections:
            infra:
                driver: 'pdo_sqlite'
                path: '%env(resolve:ADDRESS_DB_PATH)%'
    orm:
        default_entity_manager: default
        entity_managers:
            default:
                connection: infra
                mappings:
                    Addressing:
                        type: attribute
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Addressing\Entity'
                        alias: Addressing
