version: '3.8'

services:
  app:
    build: .
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      TEST_DB_DSN: 'pgsql:host=db;port=5432;dbname=addressing_test'
      TEST_DB_USER: 'addressing'
      TEST_DB_PASS: 'addressing'
    command: php vendor/bin/phpunit -c phpunit.xml.dist

  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: addressing_test
      POSTGRES_USER: addressing
      POSTGRES_PASSWORD: addressing
    ports:
      - '5432:5432'
