<?php

declare(strict_types=1);

namespace App\Addressing\Migrations;

use Doctrine\DBAL\Platforms\PostgreSQLPlatform;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260915184500CurrentBaseline extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Materialize the current Addressing ORM baseline for missing Addressing-owned tables.';
    }

    public function up(Schema $schema): void
    {
        $this->abortIf(!$this->connection->getDatabasePlatform() instanceof PostgreSQLPlatform, 'Addressing baseline supports PostgreSQL only.');
        $tables = [
            'address_city',
            'address_component',
            'address_country',
            'address_evidence_snapshot',
            'address_format',
            'address_index',
            'address_outbox',
            'address_postal_code',
            'address_province',
            'address_street',
            'address_street_type',
            'rate_limit',
        ];
        $existing = array_values(array_filter($tables, static fn (string $table): bool => $schema->hasTable($table)));
        if (count($existing) === count($tables)) { return; }
        $this->abortIf([] !== $existing, sprintf('Partial Addressing baseline detected (%d/%d tables); refusing mixed create/adopt execution.', count($existing), count($tables)));

        $this->addSql('CREATE TABLE address_city (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, country_code VARCHAR(2) NOT NULL, province_code VARCHAR(32) DEFAULT NULL, nameEntity VARCHAR(128) NOT NULL, normalized_name VARCHAR(128) DEFAULT NULL, timezone VARCHAR(64) DEFAULT NULL, uuid BYTEA NOT NULL, slug VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, modified_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_by VARCHAR(190) DEFAULT NULL, modified_by VARCHAR(190) DEFAULT NULL, active BOOLEAN DEFAULT true NOT NULL, enabled BOOLEAN DEFAULT true NOT NULL, status VARCHAR(64) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_5017D2DFD17F50A6 ON address_city (uuid)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_5017D2DF989D9B62 ON address_city (slug)');
        $this->addSql('CREATE INDEX address_city_country_name_idx ON address_city (country_code, nameEntity)');
        $this->addSql('CREATE TABLE address_component (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, address_id VARCHAR(26) DEFAULT NULL, component_type VARCHAR(64) NOT NULL, component_value VARCHAR(256) NOT NULL, normalized_value VARCHAR(256) DEFAULT NULL, source VARCHAR(64) DEFAULT NULL, confidence DOUBLE PRECISION DEFAULT NULL, uuid BYTEA NOT NULL, slug VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, modified_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_by VARCHAR(190) DEFAULT NULL, modified_by VARCHAR(190) DEFAULT NULL, active BOOLEAN DEFAULT true NOT NULL, enabled BOOLEAN DEFAULT true NOT NULL, status VARCHAR(64) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_D3BF9D1FD17F50A6 ON address_component (uuid)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_D3BF9D1F989D9B62 ON address_component (slug)');
        $this->addSql('CREATE INDEX address_component_address_type_idx ON address_component (address_id, component_type)');
        $this->addSql('CREATE TABLE address_country (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, iso2 VARCHAR(2) NOT NULL, iso3 VARCHAR(3) DEFAULT NULL, numeric_code VARCHAR(3) DEFAULT NULL, nameEntity VARCHAR(128) NOT NULL, native_name VARCHAR(128) DEFAULT NULL, phone_code VARCHAR(16) DEFAULT NULL, uuid BYTEA NOT NULL, slug VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, modified_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_by VARCHAR(190) DEFAULT NULL, modified_by VARCHAR(190) DEFAULT NULL, active BOOLEAN DEFAULT true NOT NULL, enabled BOOLEAN DEFAULT true NOT NULL, status VARCHAR(64) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8963EFED17F50A6 ON address_country (uuid)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8963EFE989D9B62 ON address_country (slug)');
        $this->addSql('CREATE INDEX address_country_iso2_idx ON address_country (iso2)');
        $this->addSql('CREATE TABLE address_format (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, country_code VARCHAR(2) NOT NULL, format_code VARCHAR(32) NOT NULL, display_pattern VARCHAR(512) NOT NULL, required_fields JSON NOT NULL, allowed_fields JSON NOT NULL, postal_code_pattern VARCHAR(128) DEFAULT NULL, example VARCHAR(512) DEFAULT NULL, uuid BYTEA NOT NULL, slug VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, modified_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_by VARCHAR(190) DEFAULT NULL, modified_by VARCHAR(190) DEFAULT NULL, active BOOLEAN DEFAULT true NOT NULL, enabled BOOLEAN DEFAULT true NOT NULL, status VARCHAR(64) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_E5E3F760D17F50A6 ON address_format (uuid)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_E5E3F760989D9B62 ON address_format (slug)');
        $this->addSql('CREATE INDEX address_format_country_code_idx ON address_format (country_code, format_code)');
        $this->addSql('CREATE TABLE address_postal_code (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, country_code VARCHAR(2) NOT NULL, postal_code VARCHAR(32) NOT NULL, province_code VARCHAR(32) DEFAULT NULL, city_name VARCHAR(128) DEFAULT NULL, latitude DOUBLE PRECISION DEFAULT NULL, longitude DOUBLE PRECISION DEFAULT NULL, uuid BYTEA NOT NULL, slug VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, modified_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_by VARCHAR(190) DEFAULT NULL, modified_by VARCHAR(190) DEFAULT NULL, active BOOLEAN DEFAULT true NOT NULL, enabled BOOLEAN DEFAULT true NOT NULL, status VARCHAR(64) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_FD57C0BDD17F50A6 ON address_postal_code (uuid)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_FD57C0BD989D9B62 ON address_postal_code (slug)');
        $this->addSql('CREATE INDEX address_postal_country_code_idx ON address_postal_code (country_code, postal_code)');
        $this->addSql('CREATE TABLE address_province (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, country_code VARCHAR(2) NOT NULL, code VARCHAR(32) NOT NULL, nameEntity VARCHAR(128) NOT NULL, type VARCHAR(32) DEFAULT NULL, uuid BYTEA NOT NULL, slug VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, modified_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_by VARCHAR(190) DEFAULT NULL, modified_by VARCHAR(190) DEFAULT NULL, active BOOLEAN DEFAULT true NOT NULL, enabled BOOLEAN DEFAULT true NOT NULL, status VARCHAR(64) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_B4552A8AD17F50A6 ON address_province (uuid)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_B4552A8A989D9B62 ON address_province (slug)');
        $this->addSql('CREATE INDEX address_province_country_code_idx ON address_province (country_code, code)');
        $this->addSql('CREATE TABLE address_street (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, country_code VARCHAR(2) NOT NULL, province_code VARCHAR(32) DEFAULT NULL, city_name VARCHAR(128) DEFAULT NULL, street_name VARCHAR(160) NOT NULL, street_type VARCHAR(32) DEFAULT NULL, normalized_name VARCHAR(160) DEFAULT NULL, uuid BYTEA NOT NULL, slug VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, modified_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_by VARCHAR(190) DEFAULT NULL, modified_by VARCHAR(190) DEFAULT NULL, active BOOLEAN DEFAULT true NOT NULL, enabled BOOLEAN DEFAULT true NOT NULL, status VARCHAR(64) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_CBB75667D17F50A6 ON address_street (uuid)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_CBB75667989D9B62 ON address_street (slug)');
        $this->addSql('CREATE INDEX address_street_lookup_idx ON address_street (country_code, city_name, street_name)');
        $this->addSql('CREATE TABLE address_street_type (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, country_code VARCHAR(2) NOT NULL, code VARCHAR(32) NOT NULL, label VARCHAR(64) NOT NULL, abbreviation VARCHAR(16) DEFAULT NULL, sort_order INT NOT NULL, uuid BYTEA NOT NULL, slug VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, modified_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_by VARCHAR(190) DEFAULT NULL, modified_by VARCHAR(190) DEFAULT NULL, active BOOLEAN DEFAULT true NOT NULL, enabled BOOLEAN DEFAULT true NOT NULL, status VARCHAR(64) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_FC903A01D17F50A6 ON address_street_type (uuid)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_FC903A01989D9B62 ON address_street_type (slug)');
        $this->addSql('CREATE INDEX address_street_type_country_code_idx ON address_street_type (country_code, code)');
        $this->addSql('CREATE TABLE address_evidence_snapshot (id VARCHAR(32) NOT NULL, owner_id VARCHAR(64) DEFAULT NULL, vendor_id VARCHAR(64) DEFAULT NULL, source_system VARCHAR(64) DEFAULT NULL, source_type VARCHAR(32) DEFAULT NULL, source_reference VARCHAR(128) DEFAULT NULL, validated_by VARCHAR(64) DEFAULT NULL, validated_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, normalization_version VARCHAR(64) DEFAULT NULL, raw_input_snapshot JSON DEFAULT NULL, normalized_snapshot JSON DEFAULT NULL, validation_status VARCHAR(16) DEFAULT \'unknown\' NOT NULL, validation_score INT DEFAULT NULL, validation_issues JSON DEFAULT NULL, provider_digest VARCHAR(64) DEFAULT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, address_id VARCHAR(26) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX address_evidence_snapshot_owner_idx ON address_evidence_snapshot (owner_id)');
        $this->addSql('CREATE INDEX address_evidence_snapshot_vendor_idx ON address_evidence_snapshot (vendor_id)');
        $this->addSql('CREATE INDEX address_evidence_snapshot_address_idx ON address_evidence_snapshot (address_id, created_at, id)');
        $this->addSql('CREATE INDEX IDX_61A49FD7F5B7AF75 ON address_evidence_snapshot (address_id)');
        $this->addSql('CREATE TABLE address_index (digest VARCHAR(64) NOT NULL, line1 VARCHAR(160) NOT NULL, line2 VARCHAR(160) DEFAULT NULL, city VARCHAR(160) NOT NULL, region VARCHAR(32) NOT NULL, postal VARCHAR(32) NOT NULL, country VARCHAR(2) NOT NULL, lat DOUBLE PRECISION DEFAULT NULL, lon DOUBLE PRECISION DEFAULT NULL, display VARCHAR(255) DEFAULT NULL, provider VARCHAR(64) DEFAULT NULL, confidence DOUBLE PRECISION DEFAULT NULL, geo_key VARCHAR(64) DEFAULT \'\' NOT NULL, created_at VARCHAR(32) NOT NULL, updated_at VARCHAR(32) NOT NULL, PRIMARY KEY (digest))');
        $this->addSql('CREATE INDEX idx_country_postal ON address_index (country, postal)');
        $this->addSql('CREATE INDEX idx_city ON address_index (city)');
        $this->addSql('CREATE INDEX idx_region ON address_index (region)');
        $this->addSql('CREATE INDEX idx_geo ON address_index (geo_key)');
        $this->addSql('CREATE TABLE address_outbox (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, stream VARCHAR(32) DEFAULT \'address\' NOT NULL, event_name VARCHAR(128) NOT NULL, event_version INT NOT NULL, payload TEXT NOT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, published_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, locked_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, locked_by VARCHAR(64) DEFAULT NULL, published_attempt INT DEFAULT 0 NOT NULL, last_error TEXT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX address_outbox_stream_created_idx ON address_outbox (stream, created_at)');
        $this->addSql('CREATE INDEX address_outbox_publish_idx ON address_outbox (published_at, locked_at, id)');
        $this->addSql('CREATE TABLE rate_limit (client VARCHAR(255) NOT NULL, rkey VARCHAR(255) NOT NULL, ts INT NOT NULL, cnt INT NOT NULL, PRIMARY KEY (client, rkey))');
        $this->addSql('ALTER TABLE address_evidence_snapshot ADD CONSTRAINT FK_61A49FD7F5B7AF75 FOREIGN KEY (address_id) REFERENCES address_entity (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->throwIrreversibleMigrationException('Current Addressing ORM baseline is the forward schema contract.');
    }
}
