# Managed by Addressing canon cleanup W02
deptrac:
    paths:
        - ../src

    exclude_files:
        - '#.*Test.*#'
        - '#.*Kernel.php#'

    layers:
        -   name: Command
            collectors:
                -   type: classNameRegex
                    value: '#^App\\Command\\.*#'

        -   name: ServiceHttp
            collectors:
                -   type: classNameRegex
                    value: '#^App\\Service\\Http\\.*#'

        -   name: Http
            collectors:
                -   type: classNameRegex
                    value: '#^App\\Http\\.*#'

        -   name: ServiceInterface
            collectors:
                -   type: classNameRegex
                    value: '#^App\\ServiceInterface\\.*#'

        -   name: Service
            collectors:
                -   type: classNameRegex
                    value: '#^App\\Service\\.*#'

        -   name: RepositoryInterface
            collectors:
                -   type: classNameRegex
                    value: '#^App\\RepositoryInterface\\.*#'

        -   name: Repository
            collectors:
                -   type: classNameRegex
                    value: '#^App\\Repository\\.*#'

        -   name: Doctrine
            collectors:
                -   type: classNameRegex
                    value: '#^App\\Doctrine\\.*#'

        -   name: Integration
            collectors:
                -   type: classNameRegex
                    value: '#^App\\Integration\\.*#'

        -   name: Contract
            collectors:
                -   type: classNameRegex
                    value: '#^App\\Contract\\.*#'

        -   name: EntityInterface
            collectors:
                -   type: classNameRegex
                    value: '#^App\\EntityInterface\\.*#'

        -   name: Entity
            collectors:
                -   type: classNameRegex
                    value: '#^App\\Entity\\.*#'

        -   name: Value
            collectors:
                -   type: classNameRegex
                    value: '#^App\\Value\\.*#'

        -   name: Projection
            collectors:
                -   type: classNameRegex
                    value: '#^App\\Projection\\.*#'

        -   name: Util
            collectors:
                -   type: classNameRegex
                    value: '#^App\\Util\\.*#'

        -   name: UtilInterface
            collectors:
                -   type: classNameRegex
                    value: '#^App\\UtilInterface\\.*#'

    ruleset:
        Command:
            - Service
            - ServiceInterface
            - RepositoryInterface
            - Contract
            - EntityInterface
            - Http
            - Value

        ServiceHttp:
            - Http
            - Service
            - ServiceInterface
            - RepositoryInterface
            - Contract
            - EntityInterface
            - Value

        Http:
            - Service
            - ServiceInterface
            - RepositoryInterface
            - Contract
            - EntityInterface
            - Value

        Service:
            - ServiceInterface
            - RepositoryInterface
            - Repository
            - Doctrine
            - Contract
            - EntityInterface
            - Entity
            - Http
            - Value
            - Integration

        Repository:
            - RepositoryInterface
            - Doctrine
            - Contract
            - EntityInterface
            - Entity
            - Value
            - Integration

        Doctrine:
            - Entity
            - EntityInterface
            - Value

        Integration:
            - Contract
            - EntityInterface
            - Entity
            - Value

        Projection:
            - Entity
            - Value
            - Integration

        Util:
            - UtilInterface

        ServiceInterface: ~
        Contract: ~
        EntityInterface: ~
        Entity: ~
        Value: ~
        RepositoryInterface:
            - Value
            - EntityInterface
        UtilInterface: ~
