# Managed by Commanding inspection
deptrac:
  paths:
    - ../src

  exclude_files:
    - '#.*Test.*#'
    - '#.*Kernel.php#'

  layers:
    - name: HttpController
      collectors:
        - type: classNameRegex
          value: '#^App\\Http\\Controller\\.*#'

    - name: Http
      collectors:
        - type: classNameRegex
          value: '#^App\\Http\\(?!Controller\\).*#'

    - name: ServiceInterface
      collectors:
        - type: classNameRegex
          value: '#^App\\ServiceInterface\\.*#'

    - name: Service
      collectors:
        - type: classNameRegex
          value: '#^App\\Service\\.*#'

    - name: RepositoryInterface
      collectors:
        - type: classNameRegex
          value: '#^App\\RepositoryInterface\\.*#'

    - name: Repository
      collectors:
        - type: classNameRegex
          value: '#^App\\Repository\\.*#'

    - name: Integration
      collectors:
        - type: classNameRegex
          value: '#^App\\Integration\\.*#'

    - name: Contract
      collectors:
        - type: classNameRegex
          value: '#^App\\Contract\\.*#'

    - name: EntityInterface
      collectors:
        - type: classNameRegex
          value: '#^App\\EntityInterface\\.*#'

    - name: Entity
      collectors:
        - type: classNameRegex
          value: '#^App\\Entity\\.*#'

    - name: Value
      collectors:
        - type: classNameRegex
          value: '#^App\\Value\\.*#'

  ruleset:
    HttpController:
      - Http
      - Service
      - ServiceInterface
      - RepositoryInterface
      - Contract
      - EntityInterface
      - Value

    Http:
      - Service
      - ServiceInterface
      - RepositoryInterface
      - Contract
      - EntityInterface
      - Entity
      - Value

    Service:
      - ServiceInterface
      - RepositoryInterface
      - Repository
      - Contract
      - EntityInterface
      - Entity
      - Value
      - Integration

    Repository:
      - RepositoryInterface
      - Contract
      - EntityInterface
      - Entity
      - Value
      - Integration
      - Service

    Integration:
      - Contract
      - EntityInterface
      - Entity
      - Value
      - Service
      - ServiceInterface
      - Repository
      - RepositoryInterface
      - Http

    Contract: ~
    ServiceInterface:
      - Contract
      - EntityInterface
      - Value
    RepositoryInterface:
      - EntityInterface
      - Contract
      - Value
    EntityInterface: ~
    Entity:
      - EntityInterface
      - Value
    Value: ~
