# Copyright (c) 2025 Oleksandr Tishchenko / Marketing America Corp

name: address-docs

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install docs dependency
        run: pip install -r docs/requirements.txt

      - name: Build docs
        run: mkdocs build --strict

      - name: Upload docs artifact
        uses: actions/upload-artifact@v4
        with:
          name: address-docs-site
          path: site/
