-- Copyright (c) 2025 Oleksandr Tishchenko / Marketing America Corp
-- Address read projection (MySQL)

CREATE TABLE IF NOT EXISTS address_projection (
  id CHAR(26) PRIMARY KEY,
  owner_id VARCHAR(64) NULL,
  vendor_id VARCHAR(64) NULL,
  line1 VARCHAR(256) NOT NULL,
  line2 VARCHAR(256) NULL,
  city VARCHAR(128) NOT NULL,
  region VARCHAR(128) NULL,
  postal_code VARCHAR(32) NULL,
  country_code CHAR(2) NOT NULL,
  line1_norm VARCHAR(256) NULL,
  city_norm VARCHAR(128) NULL,
  region_norm VARCHAR(128) NULL,
  postal_code_norm VARCHAR(32) NULL,
  latitude DOUBLE NULL,
  longitude DOUBLE NULL,
  geohash VARCHAR(32) NULL,
  validation_status VARCHAR(16) NOT NULL,
  validation_provider VARCHAR(64) NULL,
  validated_at DATETIME NULL,
  dedupe_key VARCHAR(128) NULL,
  validation_fingerprint CHAR(64) NULL,
  validation_deliverable TINYINT(1) NULL,
  validation_granularity VARCHAR(64) NULL,
  validation_quality INT NULL,
  validation_raw JSON NULL,
  validation_verdict JSON NULL,
  source_system VARCHAR(64) NULL,
  source_type VARCHAR(32) NULL,
  source_reference VARCHAR(128) NULL,
  normalization_version VARCHAR(64) NULL,
  raw_input_snapshot JSON NULL,
  normalized_snapshot JSON NULL,
  provider_digest CHAR(64) NULL,
  governance_status VARCHAR(16) NOT NULL DEFAULT 'canonical',
  duplicate_of_id CHAR(26) NULL,
  superseded_by_id CHAR(26) NULL,
  alias_of_id CHAR(26) NULL,
  conflict_with_id CHAR(26) NULL,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NULL,
  deleted_at DATETIME NULL,
  KEY address_projection_owner_idx (owner_id),
  KEY address_projection_vendor_idx (vendor_id),
  KEY address_projection_country_city_idx (country_code, city),
  KEY address_projection_country_city_norm_idx (country_code, city_norm),
  KEY address_projection_geohash_idx (geohash),
  KEY address_projection_validation_status_idx (validation_status),
  KEY address_projection_validation_deliverable_idx (validation_deliverable),
  KEY address_projection_governance_status_idx (governance_status),
  KEY address_projection_duplicate_of_idx (duplicate_of_id),
  KEY address_projection_superseded_by_idx (superseded_by_id),
  KEY address_projection_alias_of_idx (alias_of_id),
  KEY address_projection_conflict_with_idx (conflict_with_id),

  KEY address_projection_validation_status_last_idx (validation_status, last_validation_status),
  KEY address_projection_revalidation_due_idx (revalidation_due_at),
  KEY address_projection_normalization_version_idx (normalization_version),
  KEY address_projection_source_type_idx (source_type),
);
